[olr_EQ_ave, olr_std, olr_mean, eq_time] = ...
    compute_equatorial_olr('D:\project\data\1\olr_MJO.nc', 5, -5, 1979, 2014);

Seg = build_mjo_segments(olr_EQ_ave, lon, eq_time, ...
                         90, 20, 220);
